
CREATE VIEW `xsnake_xflow`.`VIEW_DEFINITION_LIST` AS
(

SELECT XD.*,

(SELECT COUNT(1) FROM XFLOW_DEFINITION_INSTANCE XDI WHERE XDI.CODE = XD.CODE ) AS VERSION_COUNT,

(SELECT COUNT(1) FROM XFLOW_PROCESS_INSTANCE XPI WHERE XPI.DEFINITION_CODE = XD.CODE ) AS BUSINESS_COUNT

FROM XFLOW_DEFINITION XD WHERE 1 = 1 ORDER BY XD.CODE

);